language: node_js

node_js:
  - 12.18.3

services:
  - postgresql

env:
  global:
    - NODE_ENV=test

before_script:
  - psql -c 'create database todo;' -U postgres

cache: npm

install:
  - npm install

script:
  - npm test

after_success: npm run coverage | coveralls
